{% set name = "PyGithub" %}
{% set version = "1.54.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 300bc16e62886ca6537b0830e8f516ea4bc3ef12d308e0c5aff8bdbd099173d4

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python >=3
    - pyjwt <2.0
    - requests >=2.14.0,<2.25
    - deprecated

test:
  requires:
    - pip
  imports:
    - github
  commands:
    - pip check

about:
  home: http://pygithub.github.io/PyGithub
  license_file: COPYING.LESSER
  license: LGPL-3.0-only
  license_family: LGPL
  summary: Python library implementing the GitHub API v3
  doc_url: http://pygithub.github.io/PyGithub
  dev_url: https://github.com/PyGithub/PyGithub

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - xmnlab
