{% set name = "PyGithub" %}
{% set version = "1.58.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7d528b4ad92bc13122129fafd444ce3d04c47d2d801f6446b6e6ee2d410235b3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python >=3
    - pyjwt >=2.0
    - pynacl >=1.4.0
    - requests >=2.14.0
    - deprecated

test:
  requires:
    - pip
  imports:
    - github
  commands:
    - pip check

about:
  home: http://pygithub.github.io/PyGithub
  license_file: COPYING.LESSER
  license: LGPL-3.0-only
  license_family: LGPL
  summary: Python library implementing the GitHub API v3
  doc_url: http://pygithub.github.io/PyGithub
  dev_url: https://github.com/PyGithub/PyGithub

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - xmnlab
