{% set name = "PyGithub" %}
{% set version = "1.43.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 095ee09abf35b3ef042c2a7143655e2df39db7a3ad213f034b0eb751e67b0b29

build:
  # Cannot use `noarch: python` as this uses 2to3.
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    
  run:
    - python
    - pyjwt
    - requests

test:
  imports:
    - github
    - github.tests

about:
  home: http://pygithub.github.io/PyGithub/v1/index.html
  license_file: COPYING.LESSER
  license: LGPL-3.0
  license_family: LGPL
  summary: 'Python library implementing the GitHub API v3'
  doc_url: http://pygithub.github.io/PyGithub/v1/index.html
  dev_url: https://github.com/PyGithub/PyGithub

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
